
---
apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: gpu
spec:
  # Enables network policy support
  networkPolicy: DefaultAllow
  # Optional: Enables logging for network policy events
  networkPolicyEventLogs: Enabled
  subnetSelectorTerms:
    - tags:
        cluster-name: "genai-apps-on-eks-april-2025"

  securityGroupSelectorTerms:
    - tags:
        cluster-name: "genai-apps-on-eks-april-2025"
  role: <ADD_NODE_ROLE>
  tags:
    model-inferencing: "gpu"
  ephemeralStorage:
    size: "400Gi"
    iops: 10000
    throughput: 512
---

apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpu
spec:
  limits:
    cpu: 256
    memory: 512Gi
  disruption:
    consolidationPolicy: WhenEmpty #or WhenEmptyOrUnderutilized
    consolidateAfter: 30s

  template:
    metadata:
      labels:
        model-inferencing: "gpu"
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: gpu
      taints:
        - key: "model-inferencing"
          value: "gpu"
          effect: NoSchedule

      expireAfter: 24h

      requirements:
        - key: eks.amazonaws.com/instance-category
          operator: In
          values:
          - g 
          - p
        - key: eks.amazonaws.com/instance-family
          operator: In
          values: ["g6", "g6e", "p4d", "p5"]

        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: eks.amazonaws.com/instance-gpu-manufacturer
          operator: In
          values: ["nvidia"]  
        - key: eks.amazonaws.com/instance-gpu-count
          operator: In
          values: ["1", "2", "4"]
