apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: langfuse
    creationTimestamp: "2025-02-20T08:18:08Z"
    labels:
      app.kubernetes.io/instance: langfuse
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: langfuse
      app.kubernetes.io/version: "3"
      helm.sh/chart: langfuse-0.12.1
    name: langfuse
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: langfuse
    creationTimestamp: "2025-02-20T08:18:08Z"
    labels:
      app.kubernetes.io/component: clickhouse
      app.kubernetes.io/instance: langfuse
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: clickhouse
      app.kubernetes.io/version: 24.12.3
      helm.sh/chart: clickhouse-7.2.0
    name: langfuse-clickhouse
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: langfuse
    creationTimestamp: "2025-02-20T08:18:08Z"
    labels:
      app.kubernetes.io/instance: langfuse
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: minio
      app.kubernetes.io/version: 2024.12.18
      helm.sh/chart: minio-14.10.5
    name: langfuse-minio
  secrets:
  - name: langfuse-minio
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: langfuse
    creationTimestamp: "2025-02-20T08:18:08Z"
    labels:
      app.kubernetes.io/instance: langfuse
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/version: 17.2.0
      helm.sh/chart: postgresql-16.4.5
    name: langfuse-postgresql
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: langfuse
    creationTimestamp: "2025-02-20T08:18:08Z"
    labels:
      app.kubernetes.io/instance: langfuse
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: valkey
      app.kubernetes.io/part-of: valkey
      app.kubernetes.io/version: 8.0.2
      helm.sh/chart: valkey-2.2.3
    name: langfuse-valkey-primary
- apiVersion: v1
  automountServiceAccountToken: false
  kind: ServiceAccount
  metadata:
    annotations:
      meta.helm.sh/release-name: langfuse
    creationTimestamp: "2025-02-20T08:18:08Z"
    labels:
      app.kubernetes.io/component: zookeeper
      app.kubernetes.io/instance: langfuse
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: zookeeper
      app.kubernetes.io/version: 3.9.3
      helm.sh/chart: zookeeper-13.7.2
      role: zookeeper
    name: langfuse-zookeeper
kind: List
metadata:
