---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-server-qwen-vision
  annotations:
    kubernetes.io/pvc-protection: "false"  
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: gp3
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-server-qwen-vision
  labels:
    app: vllm-server-qwen-vision
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-server-qwen-vision
  template:
    metadata:
      labels:
        app: vllm-server-qwen-vision
    spec:
      tolerations:
        - key: "model-inferencing"
          operator: "Equal"
          value: "gpu"
          effect: "NoSchedule"
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: vllm-server-qwen-vision
      containers:
      - name: vllm-server
        image: vllm/vllm-openai:latest
        # image: vllm/vllm-openai:v0.7.3
        command: ["/bin/sh", "-c"]
        args: [
          "vllm serve Qwen/Qwen2.5-VL-7B-Instruct --enable-auto-tool-choice --tool-call-parser hermes  --trust-remote-code --max-num-batched-tokens 8192  --max-num-seqs 8 --max-model-len 8192 --dtype bfloat16 --gpu-memory-utilization 0.95"
          
        ]
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          value: ""
        - name: VLLM_LOGGING_LEVEL
          value: "DEBUG"  
        - name: VLLM_DISABLE_COMPILE_CACHE
          value: "0"  
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 60Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: "12"
            memory: 60Gi
            nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: cache-volume
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 340
          periodSeconds: 10
          failureThreshold: 30
          successThreshold: 1

          
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 340
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: vllm-server-qwen-vision
spec:
  ports:
  - name: http-vllm-server-qwen-vision
    port: 8000
    protocol: TCP
    targetPort: 8000
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    app: vllm-server-qwen-vision
  sessionAffinity: None
  type: ClusterIP          



